# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!
import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
import numpy as np
from PyQt5 import QtCore, QtGui, QtWidgets

from Calculator import Calculator

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(721, 413)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(100, 80, 271, 261))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(48)
        self.gridLayoutWidget.setFont(font)
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.comboBox00 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox00.setObjectName("comboBox00")
        self.comboBox00.addItem("")
        self.comboBox00.addItem("")
        self.comboBox00.addItem("")
        self.comboBox00.addItem("")
        self.comboBox00.addItem("")
        self.comboBox00.addItem("")
        self.comboBox00.addItem("")
        self.comboBox00.addItem("")
        self.comboBox00.addItem("")
        self.comboBox00.addItem("")
        self.gridLayout_3.addWidget(self.comboBox00, 0, 0, 1, 1)
        self.comboBox02 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox02.setObjectName("comboBox02")
        self.comboBox02.addItem("")
        self.comboBox02.addItem("")
        self.comboBox02.addItem("")
        self.comboBox02.addItem("")
        self.comboBox02.addItem("")
        self.comboBox02.addItem("")
        self.comboBox02.addItem("")
        self.comboBox02.addItem("")
        self.comboBox02.addItem("")
        self.comboBox02.addItem("")
        self.gridLayout_3.addWidget(self.comboBox02, 0, 2, 1, 1)
        self.comboBox01 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox01.setObjectName("comboBox01")
        self.comboBox01.addItem("")
        self.comboBox01.addItem("")
        self.comboBox01.addItem("")
        self.comboBox01.addItem("")
        self.comboBox01.addItem("")
        self.comboBox01.addItem("")
        self.comboBox01.addItem("")
        self.comboBox01.addItem("")
        self.comboBox01.addItem("")
        self.comboBox01.addItem("")
        self.gridLayout_3.addWidget(self.comboBox01, 0, 1, 1, 1)
        self.comboBox11 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox11.setObjectName("comboBox11")
        self.comboBox11.addItem("")
        self.comboBox11.addItem("")
        self.comboBox11.addItem("")
        self.comboBox11.addItem("")
        self.comboBox11.addItem("")
        self.comboBox11.addItem("")
        self.comboBox11.addItem("")
        self.comboBox11.addItem("")
        self.comboBox11.addItem("")
        self.comboBox11.addItem("")
        self.gridLayout_3.addWidget(self.comboBox11, 1, 1, 1, 1)
        self.comboBox10 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox10.setObjectName("comboBox10")
        self.comboBox10.addItem("")
        self.comboBox10.addItem("")
        self.comboBox10.addItem("")
        self.comboBox10.addItem("")
        self.comboBox10.addItem("")
        self.comboBox10.addItem("")
        self.comboBox10.addItem("")
        self.comboBox10.addItem("")
        self.comboBox10.addItem("")
        self.comboBox10.addItem("")
        self.gridLayout_3.addWidget(self.comboBox10, 1, 0, 1, 1)
        self.comboBox12 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox12.setObjectName("comboBox12")
        self.comboBox12.addItem("")
        self.comboBox12.addItem("")
        self.comboBox12.addItem("")
        self.comboBox12.addItem("")
        self.comboBox12.addItem("")
        self.comboBox12.addItem("")
        self.comboBox12.addItem("")
        self.comboBox12.addItem("")
        self.comboBox12.addItem("")
        self.comboBox12.addItem("")
        self.gridLayout_3.addWidget(self.comboBox12, 1, 2, 1, 1)
        self.comboBox20 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox20.setObjectName("comboBox20")
        self.comboBox20.addItem("")
        self.comboBox20.addItem("")
        self.comboBox20.addItem("")
        self.comboBox20.addItem("")
        self.comboBox20.addItem("")
        self.comboBox20.addItem("")
        self.comboBox20.addItem("")
        self.comboBox20.addItem("")
        self.comboBox20.addItem("")
        self.comboBox20.addItem("")
        self.gridLayout_3.addWidget(self.comboBox20, 2, 0, 1, 1)
        self.comboBox21 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox21.setObjectName("comboBox21")
        self.comboBox21.addItem("")
        self.comboBox21.addItem("")
        self.comboBox21.addItem("")
        self.comboBox21.addItem("")
        self.comboBox21.addItem("")
        self.comboBox21.addItem("")
        self.comboBox21.addItem("")
        self.comboBox21.addItem("")
        self.comboBox21.addItem("")
        self.comboBox21.addItem("")
        self.gridLayout_3.addWidget(self.comboBox21, 2, 1, 1, 1)
        self.comboBox22 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox22.setObjectName("comboBox_9")
        self.comboBox22.addItem("")
        self.comboBox22.addItem("")
        self.comboBox22.addItem("")
        self.comboBox22.addItem("")
        self.comboBox22.addItem("")
        self.comboBox22.addItem("")
        self.comboBox22.addItem("")
        self.comboBox22.addItem("")
        self.comboBox22.addItem("")
        self.comboBox22.addItem("")
        self.gridLayout_3.addWidget(self.comboBox22, 2, 2, 1, 1)
        self.resetButton = QtWidgets.QPushButton(self.centralwidget)
        self.resetButton.setGeometry(QtCore.QRect(600, 20, 101, 41))
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(20)
        self.resetButton.setFont(font)
        self.resetButton.setObjectName("resetButton")
        self.calButton = QtWidgets.QPushButton(self.centralwidget)
        self.calButton.setGeometry(QtCore.QRect(500, 20, 91, 41))
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(20)
        self.calButton.setFont(font)
        self.calButton.setObjectName("calButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 30, 101, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 40, 61, 21))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(210, 40, 71, 21))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(310, 30, 71, 41))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 110, 81, 31))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 204, 71, 21))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 290, 71, 41))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(380, 20, 101, 51))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.resultText = QtWidgets.QTextBrowser(self.centralwidget)
        self.resultText.setGeometry(QtCore.QRect(410, 70, 281, 281))
        self.resultText.setObjectName("resultText")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 721, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox00.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox00.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox00.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox00.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox00.setItemText(4, _translate("MainWindow", "4"))
        self.comboBox00.setItemText(5, _translate("MainWindow", "5"))
        self.comboBox00.setItemText(6, _translate("MainWindow", "6"))
        self.comboBox00.setItemText(7, _translate("MainWindow", "7"))
        self.comboBox00.setItemText(8, _translate("MainWindow", "8"))
        self.comboBox00.setItemText(9, _translate("MainWindow", "9"))
        self.comboBox02.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox02.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox02.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox02.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox02.setItemText(4, _translate("MainWindow", "4"))
        self.comboBox02.setItemText(5, _translate("MainWindow", "5"))
        self.comboBox02.setItemText(6, _translate("MainWindow", "6"))
        self.comboBox02.setItemText(7, _translate("MainWindow", "7"))
        self.comboBox02.setItemText(8, _translate("MainWindow", "8"))
        self.comboBox02.setItemText(9, _translate("MainWindow", "9"))
        self.comboBox01.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox01.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox01.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox01.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox01.setItemText(4, _translate("MainWindow", "4"))
        self.comboBox01.setItemText(5, _translate("MainWindow", "5"))
        self.comboBox01.setItemText(6, _translate("MainWindow", "6"))
        self.comboBox01.setItemText(7, _translate("MainWindow", "7"))
        self.comboBox01.setItemText(8, _translate("MainWindow", "8"))
        self.comboBox01.setItemText(9, _translate("MainWindow", "9"))
        self.comboBox11.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox11.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox11.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox11.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox11.setItemText(4, _translate("MainWindow", "4"))
        self.comboBox11.setItemText(5, _translate("MainWindow", "5"))
        self.comboBox11.setItemText(6, _translate("MainWindow", "6"))
        self.comboBox11.setItemText(7, _translate("MainWindow", "7"))
        self.comboBox11.setItemText(8, _translate("MainWindow", "8"))
        self.comboBox11.setItemText(9, _translate("MainWindow", "9"))
        self.comboBox10.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox10.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox10.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox10.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox10.setItemText(4, _translate("MainWindow", "4"))
        self.comboBox10.setItemText(5, _translate("MainWindow", "5"))
        self.comboBox10.setItemText(6, _translate("MainWindow", "6"))
        self.comboBox10.setItemText(7, _translate("MainWindow", "7"))
        self.comboBox10.setItemText(8, _translate("MainWindow", "8"))
        self.comboBox10.setItemText(9, _translate("MainWindow", "9"))
        self.comboBox12.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox12.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox12.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox12.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox12.setItemText(4, _translate("MainWindow", "4"))
        self.comboBox12.setItemText(5, _translate("MainWindow", "5"))
        self.comboBox12.setItemText(6, _translate("MainWindow", "6"))
        self.comboBox12.setItemText(7, _translate("MainWindow", "7"))
        self.comboBox12.setItemText(8, _translate("MainWindow", "8"))
        self.comboBox12.setItemText(9, _translate("MainWindow", "9"))
        self.comboBox20.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox20.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox20.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox20.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox20.setItemText(4, _translate("MainWindow", "4"))
        self.comboBox20.setItemText(5, _translate("MainWindow", "5"))
        self.comboBox20.setItemText(6, _translate("MainWindow", "6"))
        self.comboBox20.setItemText(7, _translate("MainWindow", "7"))
        self.comboBox20.setItemText(8, _translate("MainWindow", "8"))
        self.comboBox20.setItemText(9, _translate("MainWindow", "9"))
        self.comboBox21.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox21.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox21.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox21.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox21.setItemText(4, _translate("MainWindow", "4"))
        self.comboBox21.setItemText(5, _translate("MainWindow", "5"))
        self.comboBox21.setItemText(6, _translate("MainWindow", "6"))
        self.comboBox21.setItemText(7, _translate("MainWindow", "7"))
        self.comboBox21.setItemText(8, _translate("MainWindow", "8"))
        self.comboBox21.setItemText(9, _translate("MainWindow", "9"))
        self.comboBox22.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox22.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox22.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox22.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox22.setItemText(4, _translate("MainWindow", "4"))
        self.comboBox22.setItemText(5, _translate("MainWindow", "5"))
        self.comboBox22.setItemText(6, _translate("MainWindow", "6"))
        self.comboBox22.setItemText(7, _translate("MainWindow", "7"))
        self.comboBox22.setItemText(8, _translate("MainWindow", "8"))
        self.comboBox22.setItemText(9, _translate("MainWindow", "9"))
        self.resetButton.setText(_translate("MainWindow", "重置"))
        self.calButton.setText(_translate("MainWindow", "计算"))
        self.label.setText(_translate("MainWindow", "对角线1↘"))
        self.label_2.setText(_translate("MainWindow", "第一列"))
        self.label_3.setText(_translate("MainWindow", "第二列"))
        self.label_4.setText(_translate("MainWindow", "第三列"))
        self.label_5.setText(_translate("MainWindow", "第一行"))
        self.label_6.setText(_translate("MainWindow", "第二行"))
        self.label_7.setText(_translate("MainWindow", "第三行"))
        self.label_8.setText(_translate("MainWindow", "↙对角线2"))

    def get_map(self):
        _map = np.zeros((3,3),dtype='uint8')
        _map[0,0] = int(self.comboBox00.currentText())
        _map[0,1] = int(self.comboBox01.currentText())
        _map[0,2] = int(self.comboBox02.currentText())
        _map[1,0] = int(self.comboBox10.currentText())
        _map[1,1] = int(self.comboBox11.currentText())
        _map[1,2] = int(self.comboBox12.currentText())
        _map[2,0] = int(self.comboBox20.currentText())
        _map[2,1] = int(self.comboBox21.currentText())
        _map[2,2] = int(self.comboBox22.currentText())
        print("get_map")
        print(_map)
        cal = Calculator()
        result = cal.cal(_map)
        result = list(result)
        match_str = ['第一行','第二行','第三行','第一列','第二列','第三列','对角线1','对角线2']
        result_max_index = result.index(max(result))
        result_str = '''
        结果为:
        第一行:{}
        第二行:{}
        第三行:{}
        第一列:{}
        第二列:{}
        第三列:{}
        对角线1:{}
        对角线2:{}
        你应该选择:{}
        '''.format(result[0],result[1],result[2],result[3],result[4],result[5],result[6],result[7],match_str[result_max_index])
        self.resultText.setText(result_str)
        return _map

    def clear_map(self):
        self.comboBox00.setCurrentIndex(0)
        self.comboBox01.setCurrentIndex(0)
        self.comboBox02.setCurrentIndex(0)
        self.comboBox10.setCurrentIndex(0)
        self.comboBox11.setCurrentIndex(0)
        self.comboBox12.setCurrentIndex(0)
        self.comboBox20.setCurrentIndex(0)
        self.comboBox21.setCurrentIndex(0)
        self.comboBox22.setCurrentIndex(0)

        return 0

if __name__ == "__main__":  
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)

    MainWindow.show()
    _map = ui.calButton.clicked.connect(ui.get_map)
    print("_map")
    print(_map)
    ui.resetButton.clicked.connect(ui.clear_map)
    sys.exit(app.exec_())
